defaults: &defaults
  docker:
    - image: circleci/node:8
  steps:
    - checkout
    - run: npm install

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - run: npm run test

  update_issues:
    <<: *defaults
    steps:
      - run: npm run update

workflows:
  version: 2
  commit:
    jobs:
      - test

  scheduled:
    triggers:
      - schedule:
         cron: "0 */2 * * *"
         filters:
           branches:
             only:
               - master

    jobs:
      - update_issues
