defaults: &defaults
  docker:
    - image: circleci/node:8

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run fulltest

  update_issues:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run update

workflows:
  version: 2
  commit:
    jobs:
      - test

  scheduled:
    triggers:
      - schedule:
         cron: "0 * * * *"
         filters:
           branches:
             only:
               - master

    jobs:
      - update_issues
