defaults: &defaults
  docker:
    - image: circleci/node:8

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run test-helpers
      - run: npm run test-daily-new
      - run: npm run test-weekly-new
      - store_artifacts:
          path: .artifacts

  update_daily_new:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: TRENDING_POST_COMMENTS=true TRENDING_LABEL=trending-daily node scripts/update-issues
      - store_artifacts:
          path: .artifacts

  update_weekly_new:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: TRENDING_POST_COMMENTS=true TRENDING_LABEL=trending-weekly node scripts/update-issues
      - store_artifacts:
          path: .artifacts

  clean_daily:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: TRENDING_POST_COMMENTS=true TRENDING_LABEL=trending-daily TRENDING_LANG=java node scripts/clean-issues

  update_daily:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run update-daily

  update_weekly:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run update-weekly

workflows:
  version: 2
  commit_workflow:
    jobs:
      - test

  daily_workflow:
    triggers:
      - schedule:
         cron: "0 0 * * *"
         filters:
           branches:
             only:
               - master

    jobs:
      - update_daily_new

  daily_clean_workflow:
    triggers:
      - schedule:
         cron: "0 15 * * *"
         filters:
           branches:
             only:
               - master

    jobs:
      - clean_daily

  weekly_workflow:
    triggers:
      - schedule:
         cron: "0 2 * * 5"
         filters:
           branches:
             only:
               - master

    jobs:
      - update_weekly_new
