version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install

  test:
    steps:
      - run: npm run test

  update_issues:
    steps:
      - run: npm run update

workflows:
  version: 2
  commit:
    jobs:
      - prepare
      - test:
          requires:
            - prepare

  scheduled:
    triggers:
      - schedule:
         cron: "0 */2 * * *"
         filters:
           branches:
             only:
               - master

    jobs:
      - prepare
      - update_issues:
          requires:
            - prepare
