defaults: &defaults
  docker:
    - image: circleci/node:8

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run test-daily
      - run: npm run test-weekly

  update_daily:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run update-daily

  update_weekly:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run update-weekly

workflows:
  version: 2
  commit_workflow:
    jobs:
      - test

  daily_workflow:
    triggers:
      - schedule:
         cron: "0 0 * * *"
         filters:
           branches:
             only:
               - master

    jobs:
      - update_daily

  weekly_workflow:
    triggers:
      - schedule:
         cron: "2 0 * * 5"
         filters:
           branches:
             only:
               - master

    jobs:
      - update_weekly
